# Generated by Django 5.2.5 on 2026-02-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('telefono', models.IntegerField()),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('cargo', models.CharField(choices=[('repartidor', 'Repartidor'), ('recepcion', 'Recepcion'), ('cocinero', 'Cocinero'), ('administrador', 'Administrador')], max_length=45)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones')], default='activo', max_length=25)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
            ],
            options={
                'db_table': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=45)),
                ('hora_inicio', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(max_length=1024, unique=True)),
                ('rol', models.CharField(choices=[('general', 'General'), ('otro', 'Otro')], max_length=10)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
            ],
            options={
                'db_table': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=45)),
                ('direccion', models.CharField(max_length=85)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('sucursal', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.PROTECT, to='api.sucursal')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=45)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=45)),
                ('pedido', models.OneToOneField(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='api.pedido')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(choices=[('preparacion', 'Preparación'), ('en camino', 'En camino'), ('entregando', 'Entregando'), ('completado', 'Completado')], max_length=45)),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.PROTECT, to='api.empleado')),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, to='api.pedido')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id_variante', models.AutoField(primary_key=True, serialize=False)),
                ('tamaño', models.CharField(choices=[('personal', 'Personal'), ('mediana', 'Mediana'), ('familiar', 'Familiar'), ('grande', 'Grande'), ('1/2 litro', '1/2 litro'), ('1 litro', '1 litro'), ('10 unidades', '10 unidades'), ('5 unidades', '5 unidades'), ('3 unidades', '3 unidades')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='api.producto')),
            ],
            options={
                'db_table': 'productos_variante',
                'unique_together': {('producto', 'tamaño')},
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.PROTECT, to='api.sucursal'),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='api.pedido')),
                ('variante', models.ForeignKey(blank=True, db_column='variante_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productovariante')),
                ('promocion', models.ForeignKey(blank=True, db_column='promocion_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.promocion')),
            ],
            options={
                'db_table': 'pedidos_item',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('variante__isnull', False), ('promocion__isnull', True)), models.Q(('variante__isnull', True), ('promocion__isnull', False)), _connector='OR'), name='pedido_item_tipo_unico')],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(db_column='carrito_id', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='api.carrito')),
                ('variante', models.ForeignKey(blank=True, db_column='variante_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productovariante')),
                ('promocion', models.ForeignKey(blank=True, db_column='promocion_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.promocion')),
            ],
            options={
                'db_table': 'carritos_item',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('variante__isnull', False), ('promocion__isnull', True)), models.Q(('variante__isnull', True), ('promocion__isnull', False)), _connector='OR'), name='carrito_item_tipo_unico')],
            },
        ),
        migrations.CreateModel(
            name='PromocionDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('promocion', models.ForeignKey(db_column='promocion_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='api.promocion')),
                ('variante', models.ForeignKey(db_column='variante_id', on_delete=django.db.models.deletion.PROTECT, to='api.productovariante')),
            ],
            options={
                'db_table': 'promociones_detalle',
                'unique_together': {('promocion', 'variante')},
            },
        ),
    ]
