# Generated by Django 5.2.5 on 2026-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='tamaño',
            field=models.CharField(max_length=100),
        ),
    ]
