# Generated by Django 5.2.5 on 2026-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productovariante_tamaño'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
