# Generated by Django 5.1.2 on 2024-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_repertorio_tipo_repertorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
