# Generated by Django 5.2.5 on 2026-02-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productovariante_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promociondetalle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='promociondetalle',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.categoria'),
        ),
        migrations.AddField(
            model_name='promociondetalle',
            name='tamaño',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promociondetalle',
            name='variante',
            field=models.ForeignKey(blank=True, db_column='variante_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productovariante'),
        ),
        migrations.CreateModel(
            name='CarritoItemOpcion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_promocion', to='api.carritoitem')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productovariante')),
            ],
            options={
                'db_table': 'carritos_item_opcion',
            },
        ),
        migrations.CreateModel(
            name='PedidoItemOpcion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_promocion', to='api.pedidoitem')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productovariante')),
            ],
            options={
                'db_table': 'pedidos_item_opcion',
            },
        ),
    ]
