# Generated by Django 5.1.2 on 2024-11-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertorio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
