# Generated by Django 5.1.2 on 2024-11-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_repertorio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRepertorio',
            fields=[
                ('id_detalle_repertorio', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('unidades', models.PositiveIntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('id_repertorio', models.ForeignKey(db_column='id_repertorio', on_delete=django.db.models.deletion.PROTECT, to='api.repertorio')),
            ],
            options={
                'db_table': 'detalles_repertorio',
            },
        ),
    ]
