# Generated by Django 5.2.5 on 2026-02-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_promociondetalle_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productovariante',
            name='stock',
        ),
        migrations.CreateModel(
            name='InventarioSucursal',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sucursal', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='api.sucursal')),
                ('variante', models.ForeignKey(db_column='variante_id', on_delete=django.db.models.deletion.CASCADE, related_name='stocks_sucursal', to='api.productovariante')),
            ],
            options={
                'db_table': 'inventarios_sucursal',
                'unique_together': {('sucursal', 'variante')},
            },
        ),
    ]
