# Generated by Django 5.1.2 on 2024-11-30 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_detallerepertorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('id_proventa', models.ForeignKey(db_column='id_proventa', on_delete=django.db.models.deletion.PROTECT, to='api.productoventa')),
            ],
            options={
                'db_table': 'carritos',
            },
        ),
    ]
