# Generated by Django 5.2.5 on 2026-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_productovariante_stock_inventariosucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(default='Sucursal Happy Pizza', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ofrece_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ofrece_recojo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
