# Generated by Django 5.1.2 on 2024-12-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_detallepedido_cantidad_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_cliente',
            field=models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_proventa',
            field=models.OneToOneField(db_column='id_proventa', on_delete=django.db.models.deletion.PROTECT, to='api.productoventa'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id_proventa',
            field=models.OneToOneField(db_column='id_proventa', on_delete=django.db.models.deletion.PROTECT, to='api.productoventa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_area',
            field=models.OneToOneField(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, to='api.area'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pedido',
            field=models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, to='api.pedido'),
        ),
    ]
