# Generated by Django 5.2.5 on 2026-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sucursal_nombre_sucursal_ofrece_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('recojo', 'Recojo en tienda')], default='delivery', max_length=20),
        ),
    ]
