# Generated by Django 5.1.2 on 2024-12-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paquete_cantidad_alter_carrito_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('repartidor', 'Repartidor'), ('recepcion', 'Recepcion'), ('cocinero', 'Cocinero'), ('administrador', 'Administrador')], max_length=45),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('servicio', 'Servicio'), ('no servicio', 'No Servicio'), ('despedido', 'Despedido')], default='disponible', max_length=25),
        ),
        migrations.AlterField(
            model_name='historial',
            name='detalle',
            field=models.CharField(choices=[('preparacion', 'Preparacion'), ('en camino', 'En camino'), ('entregando', 'Entregando'), ('completado', 'completado')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('deuda', 'deuda')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('digital', 'Digital')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('Cancelado', 'cancelado')], max_length=45),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('pedido', 'Pedido')], max_length=45),
        ),
    ]
