# Generated by Django 5.2 on 2026-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pedido_costo_delivery_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mercado_pago_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mercado_pago_preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
