# Generated by Django 5.1.2 on 2024-12-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_empleado_cargo_alter_empleado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerepertorio',
            name='detalle',
            field=models.CharField(choices=[('mediana', 'Mediana'), ('grande', 'Grande'), ('personal', 'Personal'), ('familiar', 'Familiar'), ('simple', 'Simple'), ('x', 'X'), ('xl', 'XL'), ('1/2 litro', '1/2 litro'), ('1 litro', '1 litro'), ('10 unidades', '10 unidades'), ('5 unidades', '5 unidades'), ('3 unidades', '3 unidades')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historial',
            name='detalle',
            field=models.CharField(choices=[('preparacion', 'Preparacion'), ('en camino', 'En camino'), ('entregando', 'Entregando'), ('completado', 'Completado')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('deuda', 'Deuda')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('Cancelado', 'Cancelado')], max_length=45),
        ),
    ]
