# Generated by Django 5.1.2 on 2024-12-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_detallerepertorio_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerepertorio',
            name='producto',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('lasagna', 'Lasagna'), ('bebida', 'Bebida'), ('agregado', 'Agregado')], max_length=100),
        ),
    ]
