# Generated by Django 5.2 on 2026-05-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pedido_cliente_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='costo_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.PROTECT, to='api.sucursal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('recojo', 'Recojo')], default='delivery', max_length=20),
        ),
    ]
