# Generated by Django 5.2 on 2026-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_pedido_cliente_alter_pedido_costo_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
