# Generated by Django 5.1.2 on 2024-12-03 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_descripcion_productoprima_tamano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='productoventa',
            name='fecha_venta',
        ),
        migrations.AddField(
            model_name='detallerepertorio',
            name='id_proprima',
            field=models.ForeignKey(blank=True, db_column='id_proprima', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productoprima'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='fecha_estado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
