# Generated by Django 5.2 on 2026-05-13 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pedido_codigo_alter_pedido_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_entrega', models.CharField(max_length=20)),
                ('costo_delivery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preference_id', models.CharField(max_length=255, unique=True)),
                ('items_snapshot', models.JSONField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('pedido_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_session', to='api.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursal')),
            ],
            options={
                'db_table': 'checkout_sessions',
            },
        ),
    ]
