# Generated by Django 5.2 on 2026-05-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_checkoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
