# Generated by Django 5.1.2 on 2024-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_repertorio_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('Cancelado', 'Cancelado')], max_length=45),
        ),
    ]
