# Generated by Django 5.1.2 on 2024-12-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_ref',
            new_name='codigo',
        ),
    ]
