# Generated by Django 5.1.2 on 2024-12-06 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_productoventa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='api.cliente'),
        ),
    ]
