# Generated by Django 5.1.2 on 2024-12-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_carrito_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id_area',
            field=models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, to='api.area'),
        ),
    ]
