# Generated by Django 5.2.5 on 2025-11-08 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_empleado_id_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRepertorio',
            fields=[
                ('id_tiporepertorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='repertorio',
            name='tipo_repertorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertorios', to='api.tiporepertorio'),
        ),
    ]
